schema_version: 1

context:
  version: 4.1.6
  build: 2
  string_prefix: 'external_'

recipe:
  name: openmpi
  version: ${{ version }}

build:
  number: ${{ build }}
  # this needs to be duplicated into output skips
  # until https://github.com/prefix-dev/rattler-build/issues/1918 is fixed
  skip: not linux

outputs:
  - package:
      name: openmpi
    build:
      string: ${{ string_prefix }}h${{ hash }}_${{ build }}
      
    requirements:
      run:
        - mpi 1.0.* openmpi
    tests:
      - script:
          - echo 'ok'

about:
  homepage: https://www.open-mpi.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: An open source Message Passing Interface implementation.
  description: |
    The Open MPI Project is an open source Message Passing Interface
    implementation that is developed and maintained by a consortium of academic,
    research, and industry partners.
  documentation: https://www.open-mpi.org/doc/
  repository: https://github.com/open-mpi/ompi

extra:
  recipe-maintainers:
    - astrofrog
    - bekozi
    - dalcinl
    - leofang
    - minrk
    - msarahan
    - ocefpaf
    - beckermr
    - j34ni
